# Generated by Django 3.0.3 on 2020-03-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(max_length=20)),
                ('area_title', models.CharField(max_length=20)),
                ('parent_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'area_data',
            },
        ),
        migrations.CreateModel(
            name='TestPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='loginfunction')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.BooleanField(default=False, verbose_name='性别')),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
